// Code generated by tools/genplugins. DO NOT EDIT.
package all

import (
	_ "github.com/anthropic/isdp/internal/service/agent/plugins/claude_code"
	_ "github.com/anthropic/isdp/internal/service/agent/plugins/hermes"
	_ "github.com/anthropic/isdp/internal/service/agent/plugins/open_claw"
	_ "github.com/anthropic/isdp/internal/service/agent/plugins/open_code"
)
