// internal/service/agent/plugins/all/all.go
// Code generated by tools/genplugins. DO NOT EDIT.
package all

// 插件包导入列表（自动生成）
import (
	_ "github.com/anthropic/isdp/internal/service/agent/plugins/claude_code"
	_ "github.com/anthropic/isdp/internal/service/agent/plugins/open_code"
)